# Generated by Django 3.0.3 on 2020-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='attachment'),
        ),
    ]
